server:
  port: 9090
mybatis-plus:
  mapper-locations: classpath*:com/design/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.design.pojo
spring:
  main:
    allow-circular-references: true
  datasource:
    username: root
    password: pinger1234567
    url: jdbc:mysql://47.113.219.144:3306/MyDesign?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.113.219.144
    port: 6379
    password: pinger1234567
    timeout: 3200
    lettuce:
      # 设置Redis连接池
      pool:
        max-wait: 2000
        min-idle: 10
        max-idle: 20
        max-active: 20
    database: 9
